version: '3.5'
services:
    php:
        image: akarendra835/laravel-kubernetes:latest
        restart: always
        ports:
            - 8000:80
        environment:
            - APP_KEY="base64:BkeEZXt7j7YzSHbswoGCSwmHKdQy8mpAj0x8hLI9vYM="
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_PORT=3306
            - DB_HOST=mysql
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
